### ISSUE TITLE
Polymorphism serialization

### ISSUE THREAD

**Issue by PMExtra** [vicenteyu/FeishuNetSdk#2]
https://github.com/vicenteyu/FeishuNetSdk/blob/f60eab35d5b3bd1afeae471352cdf0391501a361/src/Dtos/PostContent.cs#L54-L80

It cannot be serialized as expected because it should explicitly declare all the derived classes for System.Text.Json.

Reference: https://learn.microsoft.com/dotnet/standard/serialization/system-text-json/polymorphism

Now only the `Tag` property will be serialized, all other properties from the derived class will be ignored.

**Comment by vicenteyu** [comment]
已经更正此模型，并转移到Im.Dtos空间下，针对继承类型的参数需要指定类型为object。
