### ISSUE TITLE
事件回调支持

### ISSUE THREAD

**Issue by fengb3** [vicenteyu/FeishuNetSdk#6]
是否计划加入飞书事件回调功能?

**Comment by fengb3** [comment]
我用爬虫爬了飞书文档，然后我现在有所有v2事件的dto声明

**Comment by vicenteyu** [comment]
有计划做，目前还在考虑这两块内容的设计。

**Comment by fengb3** [comment]
我在我的fork里实现了的一版
支持v2版本事件
带有有一个示例webapi 工程
[https://github.com/fengb3/FeishuNetSdk/tree/feishu-event](https://github.com/fengb3/FeishuNetSdk/tree/feishu-event)

**Comment by vicenteyu** [comment]
和我想象的稍微有点不一样。
1、为方便开发，考虑使用长连接接收事件。
2、回调有限时要求，考虑和事件分开处置。

**Comment by vicenteyu** [comment]
3.0.0 已支持事件与回调。
